export const TOPICS = [
  {id: 'movie&tv', value: 'Movie & TV'},
  {id: 'music', value: 'Music'},
  {id: 'books', value: 'Books'},
  {id: 'games', value: 'Games'},
  {id: 'fashion', value: 'Fashion'},
  {id: 'food', value: 'Food'},
  {id: 'travel', value: 'Travel'},
  {id: 'sports', value: 'Sports'},
  {id: 'science', value: 'Science'},
  {id: 'technology', value: 'Technology'},
  {id: 'health', value: 'Health'},
  {id: 'business', value: 'Business'},
  {id: 'entertainment', value: 'Entertainment'},
  {id: 'art', value: 'Art'},
  {id: 'lifestyle', value: 'Lifestyle'},
  {id: 'finance', value: 'Finance'},
  {id: 'politics', value: 'Politics'},
  {id: 'religion', value: 'Religion'},
  {id: 'education', value: 'Education'},
  {id: 'others', value: 'Others'},
];
